Attribute VB_Name = "Laucher"
Global oErr As New clsErrors
Global oMysql As New clsMySQL

Global oConn As ADODB.Connection

Sub cDebug(txt As String)

    Debug.Print txt
    
End Sub

Function oTax(Code As String, Country As String) As Single

    oTax = 0.1
    
End Function

Public Function Crypt(ByVal txt As String, bEncrypt As Boolean, RegKeyType As String, PrimaryKey As String) As String

    Select Case bEncrypt
    Case False
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-86", 187)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-86", 97))) ' 187[ª] = 97[a]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-85", 208)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-85", 70))) ' 208[–] = 70[F]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-84", 176)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-84", 86))) ' 176[∞] = 86[V]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-83", 179)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-83", 60))) ' 179[≥] = 60[<]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-82", 190)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-82", 106))) ' 190[æ] = 106[j]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-81", 161)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-81", 103))) ' 161[°] = 103[g]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-80", 145)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-80", 50))) ' 145[ë] = 50[2]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-79", 207)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-79", 111))) ' 207[œ] = 111[o]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-78", 130)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-78", 108))) ' 130[Ç] = 108[l]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-77", 184)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-77", 129))) ' 184[∏] = 129[Å]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-76", 209)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-76", 127))) ' 209[—] = 127[]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-75", 156)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-75", 85))) ' 156[ú] = 85[U]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-74", 136)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-74", 99))) ' 136[à] = 99[c]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-73", 191)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-73", 112))) ' 191[ø] = 112[p]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-72", 182)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-72", 109))) ' 182[∂] = 109[m]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-71", 146)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-71", 69))) ' 146[í] = 69[E]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-70", 201)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-70", 107))) ' 201[…] = 107[k]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-69", 134)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-69", 124))) ' 134[Ü] = 124[|]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-68", 204)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-68", 54))) ' 204[Ã] = 54[6]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-67", 172)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-67", 58))) ' 172[¨] = 58[:]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-66", 185)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-66", 131))) ' 185[π] = 131[É]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-65", 217)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-65", 110))) ' 217[Ÿ] = 110[n]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-64", 170)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-64", 64))) ' 170[™] = 64[@]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-63", 137)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-63", 118))) ' 137[â] = 118[v]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-62", 183)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-62", 78))) ' 183[∑] = 78[N]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-61", 212)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-61", 115))) ' 212[‘] = 115[s]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-60", 144)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-60", 135))) ' 144[ê] = 135[á]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-59", 165)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-59", 75))) ' 165[•] = 75[K]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-58", 200)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-58", 89))) ' 200[»] = 89[Y]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-57", 216)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-57", 133))) ' 216[ÿ] = 133[Ö]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-56", 215)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-56", 66))) ' 215[◊] = 66[B]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-55", 155)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-55", 76))) ' 155[õ] = 76[L]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-54", 157)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-54", 96))) ' 157[ù] = 96[`]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-53", 180)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-53", 105))) ' 180[¥] = 105[i]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-52", 151)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-52", 104))) ' 151[ó] = 104[h]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-51", 205)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-51", 55))) ' 205[Õ] = 55[7]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-50", 186)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-50", 81))) ' 186[∫] = 81[Q]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-49", 214)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-49", 88))) ' 214[÷] = 88[X]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-48", 169)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-48", 57))) ' 169[©] = 57[9]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-47", 177)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-47", 101))) ' 177[±] = 101[e]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-46", 139)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-46", 79))) ' 139[ã] = 79[O]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-45", 181)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-45", 95))) ' 181[µ] = 95[_]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-44", 173)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-44", 121))) ' 173[≠] = 121[y]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-43", 189)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-43", 82))) ' 189[Ω] = 82[R]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-42", 152)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-42", 90))) ' 152[ò] = 90[Z]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-41", 166)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-41", 116))) ' 166[¶] = 116[t]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-40", 193)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-40", 98))) ' 193[¡] = 98[b]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-39", 135)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-39", 113))) ' 135[á] = 113[q]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-38", 199)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-38", 71))) ' 199[«] = 71[G]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-37", 192)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-37", 62))) ' 192[¿] = 62[>]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-36", 213)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-36", 119))) ' 213[’] = 119[w]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-35", 158)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-35", 102))) ' 158[û] = 102[f]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-34", 203)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-34", 92))) ' 203[À] = 92[\]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-33", 188)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-33", 77))) ' 188[º] = 77[M]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-32", 194)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-32", 128))) ' 194[¬] = 128[Ä]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-31", 150)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-31", 61))) ' 150[ñ] = 61[=]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-30", 162)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-30", 49))) ' 162[¢] = 49[1]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-29", 141)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-29", 132))) ' 141[ç] = 132[Ñ]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-28", 175)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-28", 130))) ' 175[Ø] = 130[Ç]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-27", 147)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-27", 120))) ' 147[ì] = 120[x]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-26", 196)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-26", 125))) ' 196[ƒ] = 125[}]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-25", 154)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-25", 87))) ' 154[ö] = 87[W]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-24", 140)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-24", 73))) ' 140[å] = 73[I]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-23", 178)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-23", 53))) ' 178[≤] = 53[5]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-22", 143)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-22", 51))) ' 143[è] = 51[3]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-21", 210)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-21", 83))) ' 210[“] = 83[S]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-20", 211)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-20", 93))) ' 211[”] = 93[]]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-19", 160)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-19", 122))) ' 160[†] = 122[z]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-18", 159)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-18", 84))) ' 159[ü] = 84[T]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-17", 168)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-17", 126))) ' 168[®] = 126[~]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-16", 198)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-16", 117))) ' 198[∆] = 117[u]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-15", 202)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-15", 72))) ' 202[ ] = 72[H]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-14", 138)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-14", 52))) ' 138[ä] = 52[4]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-13", 174)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-13", 56))) ' 174[Æ] = 56[8]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-12", 131)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-12", 63))) ' 131[É] = 63[?]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-11", 206)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-11", 67))) ' 206[Œ] = 67[C]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-10", 132)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-10", 123))) ' 132[Ñ] = 123[{]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-9", 195)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-9", 80))) ' 195[√] = 80[P]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-8", 133)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-8", 68))) ' 133[Ö] = 68[D]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-7", 164)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-7", 94))) ' 164[§] = 94[^]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-6", 167)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-6", 65))) ' 167[ß] = 65[A]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-5", 142)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-5", 59))) ' 142[é] = 59[;]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-4", 163)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-4", 74))) ' 163[£] = 74[J]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-3", 153)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-3", 91))) ' 153[ô] = 91[[]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-2", 149)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-2", 100))) ' 149[ï] = 100[d]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-1", 171)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-1", 134))) ' 171[´] = 134[Ü]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "B-0", 197)), Chr(GetSetting(PrimaryKey, RegKeyType, "A-0", 114))) ' 197[≈] = 114[r]
    Case True
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-86", 97)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-86", 187))) ' 97[a] = 187[ª]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-85", 70)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-85", 208))) ' 70[F] = 208[–]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-84", 86)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-84", 176))) ' 86[V] = 176[∞]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-83", 60)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-83", 179))) ' 60[<] = 179[≥]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-82", 106)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-82", 190))) ' 106[j] = 190[æ]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-81", 103)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-81", 161))) ' 103[g] = 161[°]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-80", 50)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-80", 145))) ' 50[2] = 145[ë]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-79", 111)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-79", 207))) ' 111[o] = 207[œ]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-78", 108)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-78", 130))) ' 108[l] = 130[Ç]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-77", 129)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-77", 184))) ' 129[Å] = 184[∏]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-76", 127)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-76", 209))) ' 127[] = 209[—]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-75", 85)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-75", 156))) ' 85[U] = 156[ú]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-74", 99)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-74", 136))) ' 99[c] = 136[à]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-73", 112)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-73", 191))) ' 112[p] = 191[ø]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-72", 109)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-72", 182))) ' 109[m] = 182[∂]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-71", 69)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-71", 146))) ' 69[E] = 146[í]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-70", 107)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-70", 201))) ' 107[k] = 201[…]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-69", 124)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-69", 134))) ' 124[|] = 134[Ü]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-68", 54)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-68", 204))) ' 54[6] = 204[Ã]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-67", 58)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-67", 172))) ' 58[:] = 172[¨]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-66", 131)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-66", 185))) ' 131[É] = 185[π]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-65", 110)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-65", 217))) ' 110[n] = 217[Ÿ]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-64", 64)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-64", 170))) ' 64[@] = 170[™]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-63", 118)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-63", 137))) ' 118[v] = 137[â]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-62", 78)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-62", 183))) ' 78[N] = 183[∑]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-61", 115)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-61", 212))) ' 115[s] = 212[‘]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-60", 135)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-60", 144))) ' 135[á] = 144[ê]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-59", 75)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-59", 165))) ' 75[K] = 165[•]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-58", 89)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-58", 200))) ' 89[Y] = 200[»]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-57", 133)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-57", 216))) ' 133[Ö] = 216[ÿ]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-56", 66)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-56", 215))) ' 66[B] = 215[◊]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-55", 76)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-55", 155))) ' 76[L] = 155[õ]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-54", 96)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-54", 157))) ' 96[`] = 157[ù]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-53", 105)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-53", 180))) ' 105[i] = 180[¥]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-52", 104)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-52", 151))) ' 104[h] = 151[ó]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-51", 55)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-51", 205))) ' 55[7] = 205[Õ]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-50", 81)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-50", 186))) ' 81[Q] = 186[∫]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-49", 88)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-49", 214))) ' 88[X] = 214[÷]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-48", 57)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-48", 169))) ' 57[9] = 169[©]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-47", 101)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-47", 177))) ' 101[e] = 177[±]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-46", 79)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-46", 139))) ' 79[O] = 139[ã]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-45", 95)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-45", 181))) ' 95[_] = 181[µ]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-44", 121)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-44", 173))) ' 121[y] = 173[≠]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-43", 82)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-43", 189))) ' 82[R] = 189[Ω]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-42", 90)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-42", 152))) ' 90[Z] = 152[ò]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-41", 116)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-41", 166))) ' 116[t] = 166[¶]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-40", 98)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-40", 193))) ' 98[b] = 193[¡]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-39", 113)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-39", 135))) ' 113[q] = 135[á]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-38", 71)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-38", 199))) ' 71[G] = 199[«]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-37", 62)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-37", 192))) ' 62[>] = 192[¿]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-36", 119)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-36", 213))) ' 119[w] = 213[’]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-35", 102)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-35", 158))) ' 102[f] = 158[û]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-34", 92)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-34", 203))) ' 92[\] = 203[À]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-33", 77)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-33", 188))) ' 77[M] = 188[º]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-32", 128)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-32", 194))) ' 128[Ä] = 194[¬]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-31", 61)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-31", 150))) ' 61[=] = 150[ñ]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-30", 49)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-30", 162))) ' 49[1] = 162[¢]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-29", 132)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-29", 141))) ' 132[Ñ] = 141[ç]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-28", 130)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-28", 175))) ' 130[Ç] = 175[Ø]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-27", 120)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-27", 147))) ' 120[x] = 147[ì]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-26", 125)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-26", 196))) ' 125[}] = 196[ƒ]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-25", 87)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-25", 154))) ' 87[W] = 154[ö]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-24", 73)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-24", 140))) ' 73[I] = 140[å]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-23", 53)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-23", 178))) ' 53[5] = 178[≤]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-22", 51)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-22", 143))) ' 51[3] = 143[è]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-21", 83)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-21", 210))) ' 83[S] = 210[“]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-20", 93)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-20", 211))) ' 93[]] = 211[”]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-19", 122)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-19", 160))) ' 122[z] = 160[†]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-18", 84)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-18", 159))) ' 84[T] = 159[ü]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-17", 126)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-17", 168))) ' 126[~] = 168[®]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-16", 117)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-16", 198))) ' 117[u] = 198[∆]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-15", 72)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-15", 202))) ' 72[H] = 202[ ]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-14", 52)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-14", 138))) ' 52[4] = 138[ä]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-13", 56)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-13", 174))) ' 56[8] = 174[Æ]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-12", 63)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-12", 131))) ' 63[?] = 131[É]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-11", 67)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-11", 206))) ' 67[C] = 206[Œ]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-10", 123)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-10", 132))) ' 123[{] = 132[Ñ]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-9", 80)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-9", 195))) ' 80[P] = 195[√]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-8", 68)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-8", 133))) ' 68[D] = 133[Ö]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-7", 94)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-7", 164))) ' 94[^] = 164[§]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-6", 65)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-6", 167))) ' 65[A] = 167[ß]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-5", 59)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-5", 142))) ' 59[;] = 142[é]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-4", 74)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-4", 163))) ' 74[J] = 163[£]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-3", 91)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-3", 153))) ' 91[[] = 153[ô]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-2", 100)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-2", 149))) ' 100[d] = 149[ï]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-1", 134)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-1", 171))) ' 134[Ü] = 171[´]
        txt = oMysql.ReplaceString(txt, Chr(GetSetting(PrimaryKey, RegKeyType, "A-0", 114)), Chr(GetSetting(PrimaryKey, RegKeyType, "B-0", 197))) ' 114[r] = 197[≈]
    End Select

    Crypt = txt
End Function
